spring:
  application:
    name: turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/,http://peer3:1003/eureka/

server:
  port: 1400
turbine:
  app-config: service-token
  cluster-name-expression: new String("default")
  combine-host-port: true