spring:
  application:
    name: turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/

server:
  port: 8400
turbine:
  app-config: service-token
  cluster-name-expression: new String("default")
  combine-host-port: true