spring:
  application:
    name: api-gateway
server:
  port: 1200

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/,http://peer3:1003/eureka/
zuul:
  routes:
    service-user:
      path: /user/**
      service-id: service-user
    service-token:
      path: /token/**
      service-id: service-token