spring:
  application:
    name: api-gateway
server:
  port: 2000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

zuul:
  routes:
    user:
      path: /user/**
      serviceId: service-user