
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
    register-with-eureka: false
  instance:
    hostname: peer3
spring:
  application:
    name: eureka-server