server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8002/eureka/,http://peer3:8003/eureka/
    register-with-eureka: false
  instance:
    hostname: peer1
spring:
  application:
    name: eureka-server