
server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer3:8003/eureka/
    register-with-eureka: false
  instance:
    hostname: peer2
spring:
  application:
    name: eureka-server