server:
  port: 1001
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:1002/eureka/,http://peer3:1003/eureka/
  instance:
    hostname: peer1
spring:
  application:
    name: eureka-server