
server:
  port: 1002
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer3:1003/eureka/
  instance:
    hostname: peer2
spring:
  application:
    name: eureka-server