
server:
  port: 1003
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/
  instance:
    hostname: peer3
spring:
  application:
    name: eureka-server