spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: springcloud
    password: sw2011prj
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MengStar/micro-service-lanou
          search-paths: config-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/,http://peer3:8003/eureka/
management:
  security:
    enabled: false

server:
  port: 8100
