spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: springcloud
    password: sw2011prj
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MengStar/micro-sevice-lanou
          search-paths: config-repo
          username: 641510128@qq.com
          password: sw2011prJ
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1001/eureka/,http://peer2:1002/eureka/,http://peer3:1003/eureka/

server:
  port: 1100